version: '2'

networks:
  vpcboot:
    driver: bridge
    ipam:
     config:
       - subnet: 14.5.0.0/16
         gateway: 14.5.0.1

services:
    bootlocal:
        image: businessnewapplication/bootlocal
        ports:
            - "80:8080"
        networks:
            vpcboot:
                ipv4_address: 14.5.0.6
