version: '2'

networks:
  vpcboot:
    driver: bridge
    ipam:
     config:
       - subnet: 14.5.0.0/16
         gateway: 14.5.0.1

services:
    bootlocal:
        image: bootlocal
        ports:
            - "80:8080"
        volumes:
            - ./tomcat/externo:/game/externo
#            - ./tomcat/code/target/classes/templates:/game/classes/templates
        networks:
            vpcboot:
                ipv4_address: 14.5.0.6
